# User-specific configuration override (YAML format)
# This file can be passed as a command-line argument to override settings

app_name: "MyCustomApp"
debug: true

server:
  port: 8888
  upload_dir: "./runtime-data/my-custom-example/uploads"

paths:
  data_dir: "./runtime-data/my-custom-example/data"
  cache_dir: "./runtime-data/my-custom-example/cache"
  allowed_upload_dirs:
    - "./runtime-data/my-custom-example/uploads/personal"
    - "./runtime-data/my-custom-example/uploads/work"

security:
  cert_dir: "./runtime-data/my-custom-example/certs" 
  key_file: "./runtime-data/my-custom-example/certs/personal.key"
  session_timeout: 14400  # 4 hours
  sandbox_root: "./runtime-data/my-custom-example/sandbox"

logging:
  level: "trace"
  format: "pretty"
  file_path: "custom.log"
